spring:
  application:
    name: books
  
  #profiles:
   # active: dev
  #cloud:
   # config:
    #  uri: http://localhost:8888
     # label: dev
  #config:
   # import: configserver:http://localhost:8888

server:
  port: 8080

gcp:
  project:
    id: book-store-315205